// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVJWa7jdVNTph0v0kfbrsNEHHyPkTjAGg',
    appId: '1:753864346862:android:4e042af8d77e66ad26f7ff',
    messagingSenderId: '753864346862',
    projectId: 'motolink-14e76',
    databaseURL: 'https://motolink-14e76-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'motolink-14e76.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZB7E0cxjy4PP_z6x_PecgpUE2n5ACIUg',
    appId: '1:753864346862:ios:4b544dc3c260579d26f7ff',
    messagingSenderId: '753864346862',
    projectId: 'motolink-14e76',
    databaseURL: 'https://motolink-14e76-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'motolink-14e76.firebasestorage.app',
    iosBundleId: 'com.example.motolink.motolink',
  );
}
